accounts/urls.py
from django.urls import path, re_path

from accounts import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('edit/', views.profile_edit, name='profile_edit'),
    path('password/change/', views.password_change, name='password_change'),
    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', views.user_unfollow, name='user_unfollow'),
]

django_with_react_rev2/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django_pydenticon.views import image as pydenticon_image
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', RedirectView.as_view(pattern_name='instagram:index'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('instagram/',include('instagram.urls')),
    path('indention/image/<path:data>/', pydenticon_image, name='pydenticon_image'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/urls.py
from django.urls import path, re_path
from instagram import views

app_name = 'instagram'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
]

django_with_react_rev2/templates/_form.html
{% load bootstrap5 %}
<div class="card" style="width:40em">
    {#    form_title이 존재한다면 card-header를 보이게하고 아니면 보이게하지않는다.#}
    {% if form_title %}
        <div class="card-header">
            {{ form_title }}
        </div>
    {% endif %}

    <div class="card-body">
        {#                                        사진을 사용할땐 enctype="multipart/form-data"필수#}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {#                                                    submit_label이 존재한다면 submit_label를 보여주고 아니면 'Submit'을 보여줌#}
            <input class="btn btn-primary" type="submit" value="{{ submit_label|default:'Submit' }}">
        </form>
    </div>
</div>

django_with_react_rev2/templates/layout.html
{% load static bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Instagram With 2023 Project</title>
    <link rel="stylesheet" href="{% static "bootstrap-5.2.3-dist/css/bootstrap.min.css" %}">
    <script src="{% static "jquery-3.6.1.min.js" %}"></script>
    <script src="{% static "jquery.form-4.3.0.min.js" %}"></script>
    <script src="https://kit.fontawesome.com/a6cbf64ff7.js" crossorigin="anonymous"></script>
</head>
{% bootstrap_messages %}
<div class="border-bottom mb-3">
    <div class="container">
        <div class="col-sm-12">
            <div class="d-flex flex-column flex-md-row align-items-center mt-3 pb-3  ">
                <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                    <img src="{% static 'instagram_logo.png' %}" alt="instagram" width="100px">
                </a>


                <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                    {% if user.is_authenticated %}
                        <a class="me-3 py-2 text-dark text-decoration-none"
                           href="{% url 'accounts:logout' %}">Logout</a>
                        <a class="me-3 py-2 text-dark text-decoration-none"
                           href="{% url 'instagram:user_page' user.username %}">
                            <img class="rounded-circle" src="{{ user.avatar_url }}" alt="None" width="24px;">
                            {{ user.username }}
                        </a>
                    {% else %}
                        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:login' %}">Login</a>
                        <a class="me-3 py-2 text-dark text-decoration-none"
                           href="{% url 'accounts:signup' %}">Signup</a>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
</div>



{% block content %}
{% endblock content %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <img class="mb-2" src="/docs/5.2/assets/brand/bootstrap-logo.svg" alt="" width="24" height="19">
            <small class="d-block mb-3 text-muted">© 2017–2022</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none"
                                    href="{% url 'accounts:login' %}">Login</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>