accounts/urls.py
from django.urls import path, re_path

from accounts import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('edit/', views.profile_edit, name='profile_edit'),
    path('password/change/', views.password_change, name='password_change'),
    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', views.user_unfollow, name='user_unfollow'),
]

instagram/urls.py
from django.urls import path, re_path
from instagram import views

app_name = 'instagram'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
]

instagram/models.py
import re
from django.db import models
from django.conf import settings
from django.urls import reverse


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # 추상메소드 : abstract = True, class를 다른 곳에 상속시켜야 할 때 사용


class Post(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="my_post_set")
    photo = models.ImageField(upload_to="instagram/post/%Y/%m/%d")
    caption = models.CharField(max_length=500)  # 사진설명
    location = models.CharField(max_length=100)  # 위치
    tag_set = models.ManyToManyField('Tag', blank=True)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post_set')

    class Meta:
        # ordering : 정렬 / +은 직렬화 정렬(기본값) , -는 역순화 정렬
        ordering = ['-pk']

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

    # caption에서 tag삭제하고 글씨만 남기는 함수
    def caption_replace(self):
        caption = re.sub(r"#([a-zA-z\dㄱ-힣]+)", "", self.caption).strip()
        self.caption = caption
        return self.caption

    # caption에서 tag를 쓸 수 있게 하는 함수
    def extract_tag_list(self):
        # re.findall() : 정규표현식에 해당하는 것들을 전부 찾아온다.
        tag_name_list = re.findall(r"#([a-zA-z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(
                name=tag_name)  # name에 tag_name_list에서 순차적으로 다시 담은 tag_name을 넣어준다.
            tag_list.append(tag)  # append : 리스트에 변수를 넣어주는 역할
        return tag_list

    def is_like_user(self, user):
        # 현재 로그인한 유저가 좋아요한 포스팅의 존재여부를 확인
        # exists() : 존재한다면 True 아니라면 False
        return self.like_user_set.filter(pk=user.pk).exists()

    def __str__(self):
        return self.caption
    #     def __str__(self):
    #         # caption : 웰시코기
    #         # Post objects (1) - admin 페이지
    #         # __str__ 의  self.caption 사용후 / Post objects (1) > 웰시코기
    #         return self.caption


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Comment(BaseModel): # BaseModel엔 comment_set 내장되어있나? 뭐지 pk도 그냥 넘겨주나
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    messages = models.TextField()  # 댓글메세지

    class Meta:
        ordering = ['-pk']

instagram/forms.py
from django import forms

from instagram.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location']
        widgets = {
            'caption': forms.Textarea,
        }


# detail, comment_new , index view에서 사용
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['messages']
        widgets = {
            'messages': forms.Textarea(attrs={"rows": 3})
        }

instagram/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from instagram.models import Post
from accounts.models import User
from instagram.forms import CommentForm, PostForm


@login_required
def index(request):
    post_list = Post.objects.filter(author=request.user)

    suggested_user_list = get_user_model().objects.all() \
        .exclude(pk=request.user.pk) \
        .exclude(pk__in=request.user.following_set.all())

    form = CommentForm()
    # 작성해주지 않으면 유효한 폼이 필요하다고 에러남
    # index html에서 comment관련 card를 include 해주므로 여기서도 CommentForm()이 필요하다.
    return render(request, 'instagram/index.html', {
        'post_list': post_list,
        'suggested_user_list': suggested_user_list,
        'form': form,

    })


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # commit?
            post.author = request.user
            post.save()
            post.tag_set.add(
                *post.extract_tag_list())
            # post.caption_replace() # 글씨 삭제하고 tag만 남기는 함수
            post.caption_replace()
            post.save()
            return redirect('/')
    else:
        form = PostForm()

    return render(request, 'instagram/post_form.html', {
        'form': form
        # 컨텍스트는 설정된 것이 아니라 딕트(사전형식)여야 합니다.
    })


@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm()
    return render(request, 'instagram/post_detail.html', {
        'post': post,
        'form': form,
    })


@login_required
def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    post_list = Post.objects.filter(author=page_user)
    post_list_count = post_list.count()  # 게시글 개수 반환
    follower_count = page_user.follower_set.count()
    following_count = page_user.following_set.count()
    if request.user.is_authenticated:
        is_follow = page_user.follower_set.filter(pk=request.user.pk).exists()
        # 유저 페이지에 들어갔을 때 요청 유저의 following_set에 접근 유저의 pk기 있다면 팔로우 상태임을 알 수 있다.
        # 한마디로 로그인, 인증 상태가 아니라면 겸상조차 불가능함. 이걸로 어떻게 써먹는지 다시 생각해보기
    else:
        is_follow = False

    return render(request, 'instagram/user_page.html', {
        'page_user': page_user,
        'post_list': post_list,
        'post_list_count': post_list_count,
        'follower_count': follower_count,
        'following_count': following_count,
        'is_follow': is_follow,

    })


@login_required()
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)
    messages.success(request, f'{post.pk}번 게시물에 좋아요 완료되었습니다.')
    redirect_url = request.META.get('HTTP_REFERER', 'root')
    return redirect(redirect_url)


@login_required()
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)
    messages.success(request, f'{post.pk}번 게시물 좋아요 취소되었습니다.')
    redirect_url = request.META.get('HTTP_REFERER', 'root')
    return redirect(redirect_url)


@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)  # commit?
            comment.author = request.user
            comment.post = post  # comment의 post위치 정해주기, post는 위에서 정의한 post임
            comment.save()
            # 아래 부분은 ajax를 이용할 때 써야됨. ajax 요청을 받으면 실행됨
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return render(request, 'instagram/_comment.html', {
                    'comment': comment,
                })
            return redirect(comment.post)

    else:
        form = CommentForm()
    return render(request, 'instagram/_comment.html', {
        'form': form,
    })

instagram/templates/instagram/_comment.html
{% load humanize %}
<div class="comment">
    <strong>{{ comment.author }}</strong>
    {{ comment.messages }}
    <small class="text-muted">{{ comment.created_at|naturalday }}</small>
</div>

instagram/templates/instagram/_post_card.html
{% load bootstrap5 humanize %}
{% load instagram_tags %}
<div class="card my-3">
    <div class="card-header">
        <img src="{{ post.author.avatar_url }}" alt="None avatar" width="24px" height="24px">
        {{ post.author.name }}
    </div>
    <div class="card-body">
        <div>
            <img src="{{ post.photo.url }}" alt="None" style="width:60%;">

        </div>
        <div class="my-3">
            <div>
                {% if post|is_like_user:user %}
                    <a id="test" class="text-dark"
                       href="{% url 'instagram:post_unlike' post.pk %}">
                        <i class="fa-solid fa-heart"></i>
                    </a>
                {% else %}
                    <a id="test" class="text-dark"
                       href="{% url 'instagram:post_like' post.pk %}">
                        <i class="fa-regular fa-heart"></i>
                    </a>
                {% endif %}
            </div>
            <div>
                {{ post.caption }}
                <a class="text-muted text-decoration-none" href="{{ post.get_absolute_url }}">
                    <span class="text-muted">{{ post.created_at|naturaltime }}</span>
                    {# created_at- instagram model의 필드 naturaltime:humanize 기능  #}
                </a>
            </div>
            <div>
                {% for tag in post.tag_set.all %}
                    <span class="badge bg-black">#{{ tag.name }}</span>
                {% endfor %}
            </div>
            <div id="-post-{{ post.pk }}-comment-list" class="my-3">
                {% for comment in post.comment_set.all %}
                    {% include 'instagram/_comment.html' %}
                {% endfor %}
            </div>
        </div>

    </div>
    <div class="card-footer">
        <div>
            <form id="-post-{{ post.pk }}-comment-form" action="{% url 'instagram:comment_new' post.pk %}"
                  method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input class="btn" type="submit" value="작성">
            </form>
        </div>
        <script>
            $(function(){
                let form_id = '-post-{{ post.pk }}-comment-form';
                let comment_id = '-post-{{ post.pk }}-comment-list';
                $('#'+form_id).submit(function (e){
                    e.preventDefault();

                    let options={
                        success: function (responseText,statusText,xhr,$form){
                            console.group("ajaxSubmit response")
                            console.log(responseText);
                            console.log(statusText);
                            console.log(xhr);
                            console.log($form);
                            console.groupEnd();
                            $('#'+comment_id).prepend(responseText);
                        }
                    }
                    $(this).ajaxSubmit(options);
                })
                console.log('document ready')
            })
        </script>

    </div>
</div>

instagram/templates/instagram/index.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <a class="btn d-grid col-sm-6 offset-3 " href="{% url 'instagram:post_new' %}" style="background-color: #f5c2c7; color: #ffffff;">새 포스팅 쓰기</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                {% for post in post_list %}
                    {% include 'instagram/_post_card.html' %}
                {% endfor %}
            </div>
            <div class="col-sm-4">
                {% include 'instagram/timeline_sidebar.html' %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/layout.html
{% extends 'layout.html' %}

instagram/templates/instagram/post_detail.html
{% extends 'instagram/layout.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include 'instagram/_post_card.html' %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}
{% load bootstrap5 %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-3">
                {# include : 부분을 통째로 가져옴#}
                {% include '_form.html' with form_title='새 포스팅 쓰기' submit_label='작성' %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/timeline_sidebar.html
<div class="d-flex p-2 my-3">
    <div class="me-2">
        <img class="rounded-circle" src="{{ user.avatar_url }}" alt="None" width="48px;" height="48px;">
    </div>
    <div class="me-2">
        {{ user.username }}<br> {# 아이디를뜻하고  #}
        <small class="text-muted">{{ user.name }}님</small> {# 모델에서 설정한 name class를 뜻한다. #}
    </div>
</div>

<div class="card mb-3">
    <div class="card-header">
        Stories
    </div>
    <div class="card-body">
        stories form people you follow will show up here.
    </div>
</div>

<div class="card mb-3">
    <div class="card-header">
        Suggestions for you
    </div>
     <div class="card-body text-muted">
        {% for suggested_user in suggested_user_list %}
            {% include 'instagram/timeline_sidebar_userfollow.html' %}
        {% endfor %}
    </div>
</div>

instagram/templates/instagram/timeline_sidebar_userfollow.html
<div class="d-flex mb-1">
    <div class="me-2">
        <a href="{% url 'instagram:user_page' suggested_user.username%}">
            <img class="rounded-circle" src="{{ suggested_user.avatar_url }}" alt="None" height="48px;" width="48px;">
        </a>
    </div>

    <div class="mt-2">
        <a class="text-dark text-decoration-none" href="{% url 'instagram:user_page' suggested_user.username %}">{{ suggested_user.name }}</a>
    </div>
    <div class="ms-2 mt-2">
       <a class="text-decoration-none " style="color: #d63384; " href="{% url 'accounts:user_follow' suggested_user.username %}"> Follow me </a>
    </div>
</div>

instagram/templates/instagram/user_page.html
{% extends 'instagram/layout.html' %}
{% load thumbnail %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <img class="rounded-circle" src="{{ page_user.avatar_url }}" alt="None" width="240px">
            </div>
            <div class="col-sm-9">
                {{ page_user.username }}
                {% if page_user == user %}
                    <a class="btn btn-secondary" href="{% url 'accounts:profile_edit' %}">프로필 수정</a>
                    <a class="btn btn-secondary" href="{% url 'accounts:password_change' %}">비밀번호 변경</a>
                {% else %}
                    {% if is_follow %}
                        <a class="btn btn-primary" href="{% url 'accounts:user_unfollow' page_user.username %}">언팔로우</a>
                    {% else %}
                        <a class="btn btn-primary " href="{% url 'accounts:user_follow' page_user.username %}">팔로우</a>
                    {% endif %}
                {% endif %}
                <hr>
                {{post_list_count}} post , {{ following_count }} following , {{ follower_count }} follower
                <hr>
                {{ page_user.name }}
            </div>



        </div>
        <hr>
        <div class="row my-5">
            {% for post in post_list %}
               <div class="col-3 py-4 mb-2">
                    <a href="{{ post.get_absolute_url }}">
                        <img src="{% thumbnail post.photo 256x256 crop%}" alt="None">
                    </a>
               </div>
            {% endfor %}
        </div>

    </div>
{% endblock content %}